name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yaml
  tag:
    name: Tag
    needs: test
    permissions:
      contents: write
    uses: ./.github/workflows/tag.yaml
  publish-npm:
    name: Publish packages to NPM
    needs: tag
    if: needs.tag.outputs.new-version != ''
    uses: ./.github/workflows/publish-packages.yaml
    secrets: inherit
    with:
      version: ${{ needs.tag.outputs.new-version }}
      registry: npm
      publish-command: pnpm -r exec pnpm publish --access public
