name: Test
on:
  workflow_call:
    inputs:
      timeout-minutes:
        required: false
        type: number
        default: 3
      test-command:
        required: false
        type: string
        default: 'pnpm test'
      setup-protoc:
        required: false
        type: boolean
        default: false
    outputs:
      new-version:
        value: ${{ jobs.tag.outputs.new-version }}
      new-major-version:
        value: ${{ jobs.tag.outputs.new-major-version }}
jobs:
  test:
    name: Test
    timeout-minutes: ${{ inputs.timeout-minutes }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up
        uses: mtth/sdk.ts/.github/actions/setup@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          node-auth-token: ${{ secrets.GPR_RO_TOKEN }}
          setup-protoc: ${{ inputs.setup-protoc }}
      - name: Lint
        run: pnpm run lint
      - name: Test
        run: ${{ inputs.test-command }}
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: out/coverage
