name: Test
on:
  workflow_call:
    inputs:
      timeout-minutes:
        required: false
        type: number
        default: 3
      bump-version:
        required: false
        type: boolean
        default: false
      test-command:
        required: false
        type: string
        default: 'pnpm test'
      setup-protoc:
        required: false
        type: boolean
        default: false
      services-file:
        required: false
        type: string
        default: ''
    outputs:
      new-version:
        value: ${{ jobs.tag.outputs.new-version }}
      new-major-version:
        value: ${{ jobs.tag.outputs.new-major-version }}
jobs:
  test:
    name: Test
    timeout-minutes: ${{ inputs.timeout-minutes }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up
        uses: mtth/sdk.ts/.github/actions/setup@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          node-auth-token: ${{ secrets.GPR_RO_TOKEN }}
          setup-protoc: ${{ inputs.setup-protoc }}
      - name: Lint
        run: pnpm run lint
      - name: Log in to GCR
        if: inputs.services-file != ''
        uses: docker/login-action@v3
        with:
          username: mtth
          password: ${{ secrets.GPR_RO_TOKEN }}
          registry: ghcr.io
      - name: Set up services
        if: inputs.services-file != ''
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          up-flags: --wait
          compose-file: ${{ inputs.services-file }}
      - name: Test
        run: ${{ inputs.test-command }}
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: out/coverage
  tag:
    name: Tag
    runs-on: ubuntu-latest
    if: inputs.bump-version
    needs: test
    permissions:
      contents: write
    outputs:
      new-version: ${{ steps.bump-version.outputs.new_version }}
      new-major-version: ${{ steps.extract-major-version.outputs.version }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Bump version and create tag
        id: bump-version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
          custom_release_rules: build:patch,deps:patch,refactor:patch
      - name: Extract major version
        id: extract-major-version
        if: steps.bump-version.outputs.new_version != ''
        run:
          echo "version=${PACKAGE_VERSION%%.*}" >>"$GITHUB_OUTPUT"
        env:
          PACKAGE_VERSION: ${{ steps.bump-version.outputs.new_version }}
